articles/urls.py
from django.urls import path
from django.conf.urls import url
from .views import (
    articles, article_details,create_article, delete_article,articles_update
)


app_name='articles'

urlpatterns = [
    path('', articles, name="list"),
    url(r'^create_article/$',create_article, name="create_article"),
    url(r'^(?P<slug>[\w-]+)/delete/$', delete_article),
    url(r'^(?P<slug>[\w-]+)/edit/$', articles_update, name='edit'),
    url(r'^(?P<slug>[\w-]+)/$', article_details, name="detail"),
]

cnewsww/urls.py
from django.urls import path, include
from django.urls import path
from .import views

app_name='cryptos'
urlpatterns = [
    path('', views.home, name='home'),
    path('single/', views.data, name='single')
]

cnww/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
import cnewsww.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cnewsww.views.home, name='home'),
    path('articles/', include('articles.urls'))
]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

articles/models.py
from __future__ import unicode_literals
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import pre_save
from django.utils.text import slugify
from django.utils import timezone
from django.contrib import admin
from .utils import get_unique_slug

#this filters the unpublished contents from the published ones
class ArticleFilter(models.Manager):
    def active(self, *args, **kwargs):
        return super(ArticleFilter,self).filter(draft=False).filter(publish__lte=timezone.now())


#this changes the uploaded location
def upload_location(instance, filename):
    return "%s/%s" %(instance.id, filename)

# Create your models here.
class Tag(models.Model):
    type = models.CharField(max_length=100)
    tag = models.CharField(max_length=100)
    def __str__(self):
        return self.tag

class Author(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    def __str__(self):
        return self.name

class Entry(models.Model):
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE)
    title=models.CharField(max_length=50)
    slug=models.SlugField(max_length=50, unique=True)
    body=models.TextField(max_length=2000)
    authors = models.ManyToManyField(Author)
    draft=models.BooleanField(default=False)#controls whether content is in draft or not
    publish=models.DateField(auto_now=False, auto_now_add=False)
    image=models.ImageField(upload_to= 'static/media', default='blog.png',null=True, blank=True,
          width_field="width_field",
          height_field="height_field")
    width_field=models.IntegerField(default=0)
    height_field=models.IntegerField(default=0)
    updated= models.DateTimeField(auto_now=True, auto_now_add=False)
    timestamp= models.DateTimeField(auto_now=False, auto_now_add=True)

    objects=ArticleFilter()

    def summary(self):
        return self.body[:100]

    def __unicode__(self):
        return self.title

    def pub_date_pretty(self):
       return self.timestamp.strftime('%b %e %Y')

    #shows the content's title in the admin instead of object list
    def __str__(self):
        return self.title

    #this makes it possible for the created article to find the right path to the database
    def get_absolute_url(self):
       return reverse("articles:detail",kwargs={"slug":self.slug})

cnewsww/models.py
from django.db import models

# Create your models here.

articles/forms.py
from django import forms
from .models import Entry, Tag

class ArticleForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=["tag","title","image","slug", "body","authors", "draft", "publish",]

articles/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Entry
from .forms import ArticleForm
from django.utils.http import quote
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.contrib import messages
from django.db.models import Q
from django.utils import timezone
from django.utils.http import quote_plus

# Create your views here.

def articles(request):
    todayDate=timezone.now().date()
    article_list=Entry.objects.active().order_by("-timestamp")
    if request.user.is_staff or request.user.is_superuser:
        article_list=Entry.objects.all()

    #searches through the post
    query=request.GET.get("quote")
    if query:
        article_list=article_list.filter(
            Q(title__icontains=query)| 
            Q(body__icontains=query)| 
            Q(authors__name__icontains=query)
            ).distinct()

    #this manages the pagination
    paginator= Paginator(article_list, 12)
    page_request_var="page"
    page=request.GET.get(page_request_var)
    try:
        queryset=paginator.get_page(page)
    except PageNotAnInteger:
        queryset=paginator.page(1)
    except EmptyPage:
        queryset=paginator.page(paginator.num_pages)

    context={
    "today": todayDate,
    "article_list":article_list,
    "page_request_var":page_request_var,
     "object_list":queryset,
    }
    return render(request, 'articles/articles.html', context)


def create_article(request):
    #checks the users level
    form=ArticleForm(request.POST or None)
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404

    if form.is_valid():
        instance=form.save(commit=False)#confirms the goodness of the data
        instance.user=request.user#bring forth the logged-in user
        instance.save()#saves the data into the database
        messages.success(request, "Created Successfully")
        return HttpResponseRedirect(instance.get_absolute_url())
    article_form = {"form": form, }
    return render(request, "articles/create_article.html", article_form)

def article_details(request, slug):
        articles=Entry.objects.get(slug=slug)
        return render(request, 'articles/articles_details.html', {'fullarticle':articles})

def articles_update(request, slug=None):
    # checks the users level
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    articleUpdater=get_object_or_404(Entry, slug=slug)
    form = ArticleForm(request.POST or None,request.FILES or None, instance=articleUpdater)
    if form.is_valid():
        articleUpdater = form.save(commit=False)  # confirms the goodness of the data
        articleUpdater.save()  # saves the data into the database
        messages.success(request, "<a href='#'>Item</a> Saved", extra_tags='html_safe')
        return HttpResponseRedirect(articleUpdater.get_absolute_url())#redirects after Successfully sent to DB
    context ={"title":articleUpdater.title, "instance":articleUpdater, "form":form}

    return render(request, 'articles/create_article.html', context)

def delete_article(request, slug=None):
    # checks the users level
    if not request.user.is_superuser:
        messages.success(request, "<h2>Sorry cannot find the page you are looking for</h2>", extra_tags='html_safe')
        return redirect("articles:list")
    getter=get_object_or_404(Entry, slug=slug)
    getter.delete()
    messages.success(request, "Deleted Successfully")
    return redirect("articles:list")

cnewsww/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from urllib import request
import requests
import json

def home(request):

    # this fetch the crypto table
    data_request =requests.get("https://min-api.cryptocompare.com/data/pricemultifull?fsyms=BTC,DASH,ZEC,ETH,LTC,DOGE,BAT,XMR,BCH,NEO,ADA,XRP&tsyms=USD")
    table_data = json.loads(data_request.content)
    # this fetch the news update
    api_request =requests.get("https://min-api.cryptocompare.com/data/v2/news/?lang=EN")
    api_content = json.loads(api_request.content)
    collector={
        'api': api_content, 'data': table_data
        }
    return render(request, 'cnewsww/home.html', collector)

articles/templates/articles/articles.html
{% extends 'articles/base.html'%}
{% load bootstrap4 %}
{% load staticfiles %}


{%block article_short%}
      <div class="album py-5 bg-gray">
        <div class="container">
            <div class="row">
                {% for articles in article_list.all%}
                <div class="col-md-4">
                    <div class="card mb-4 shadow-sm">
                        <div class="card-body image-height">
                            <p class="card-text">
                                {{articles.pub_date_pretty}}</br>
                                <h2><a href="{%url 'articles:detail' slug=articles.slug%}">{{articles.title}}</br></a></h2></br>
                                <img class="img-fluid img-responsive" src="{{articles.image.url}}" height="150" width="200" /></br>
                                {{articles.summary}}
                                {{articles.authors.name}}
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group">
                                    <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{%url 'articles:detail' slug=articles.slug%}">Read more...</a></button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {%endfor%}
                <div class="pagination">
                    <span class="step-links">
                        {% if article_list.has_previous%}
                        <a href="?page=1">&laquo; first</a>
                        <a href="?page={{ article_list.previous_page_number }}">previous</a>
                        <!--<a href="?{{page_request_var}} ={{article_list.previous_page_number}}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">previous</a>-->
                        <span class="current">
                            Page {{ article_list.number }} of {{ article_list.paginator.num_pages }}
                            <!--page {{article_list.number}} of {{article_list.pagination.num_pages}}-->
                        </span>
                        {% endif %}
                        {% if article_list.has_next %}
                        <a href="?page={{ article_list.next_page_number }}">next</a>
                        <a href="?page={{ article_list.paginator.num_pages }}">last &raquo;</a>
                        <!-- <a href="?{{page_request_var}} = {{article_list.next_page_number}}{%if request.GET.q%}&q={{request.GET.q}}{%endif%}">next</a>-->
                        {% endif%}
                    </span>
                </div>
            </div>
        </div>
      </div>
{%endblock%}

articles/templates/articles/articles_details.html
{% extends "articles/base.html" %}
{% load bootstrap4 %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static 'css/style.css' %}">

  {%block slideshow%}
 {% for articles in article_list.all%}
    <div class="col-md-4">
        <div class="card mb-4 shadow-sm">
            <div class="card-body image-height">
                <p class="card-text">
                    {{articles.pub_date_pretty}}</br>
                    <h2><a href="{%url 'articles:detail' slug=articles.slug%}">{{articles.title}}</br></a></h2></br>
                    <img class="img-fluid img-responsive" src="{{articles.image.url}}" height="150" width="200" /></br>
                    {{articles.summary}}
                    {{articles.authors.name}}
                </p>
                <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                        <button type="button" class="btn btn-sm btn-outline-secondary"><a href="{%url 'articles:detail' slug=articles.slug%}">Read more...</a></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
  {%endfor%}
  {%endblock slideshow%}

{%block article_full%}
{{title}}
<div class="col-sm-6 col-sm-offset-3 container justify-content-center">
    {%if fullarticle.first_name%}
    <strong>Author</strong>:{{ fullarticle.author.first_name }}<br />
    {%endif%}
    <h2>{{fullarticle.title}}</h2></br>

    {%if fullarticle.image%}
    <img src="{{fullarticle.image.url}}" height="300" width="400" class="img-responsive" /><br />
    {%endif%}
    {{fullarticle.pub_date_pretty}}<br />
    <h1>{{title}}<small>{{fullarticle.timestamp}}</small></h1><br />
    <div class="container justify-content-left"><p class="text-center">{{fullarticle.body|linebreaks}}</p></br></div>
    <a class="btn btn-secondary my-2" href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}">
        Share On Facebook
    </a></br>
    <div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-colorscheme="dark" data-numposts="5"></div>
</div>
{%endblock article_full%}

articles/templates/articles/base.html
{% load bootstrap4 %}
{% load staticfiles %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!--<link rel="icon" href="../../../../favicon.ico">-->

    <title>CNWW website</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <script src="{%static 'js/jquery.js'%}"></script>

</head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="/articles">CNWW Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link" href="http://localhost:8000/">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link active" href="/articles">Blog</a>
          </div>
        </div>
      </nav>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">I am a software enthusiast with persionate interest in how Cryptocurrencies can help improve daily living.</p>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-dark bg-dark">
        <form method="GET" action="" class="form-inline">
          {%csrf_token%}
          <input class="form-control mr-sm-2" type="search"  name="quote" placeholder="content, title, author" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit" value='{{request.GET.quote}}'>Search Blog</button>
        </form>
      </nav>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>

      <div class="jumbotron container-fluid">
        <h1 class="display-3">Welcome to CNWW Blog!</h1>
        <p class="lead">Here you can get latest blog posts from CNWW and advice on the crypto investment</p>
        <hr class="my-4">
        <!--<p>If you find this website helpful, $5 USD worth of crypto currency will really go a long way for us</p>-->
        <div col-sm-4 offset-md-1 py-4><h4 class="textContact text-center">Contact Us</h4>
          <p class="lead">
            <a class="btn btn-primary btn-lg" target="_blank" href="#" role="button">E-Mail</a>
            <a class="btn btn-primary btn-lg" target="_blank" href="#" role="button">Facebook</a>
            <a class="btn btn-primary btn-lg" target="_blank" href="#" role="button">Twitter</a>
        </p>
       </div>
      </div>
      {%block article_title%}
      {%endblock%}

      <div class="blog-header">
        <div class="container">
          <h1 class="blog-title">The CNWW Blog</h1></br>
          <p class="lead blog-description">
          <div id="fb-root"></div>
          <script async defer crossorigin="anonymous" src="https://connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v3.2"></script>
          <div id="fb-root"></div>
         <div class="container justify-content-left">
           <p>
          {% block article_full%}
          {%endblock%}

          {%block article_short%}
          {%endblock%}

          {%block article_form%}
          {%endblock article_form%}

          {%block slideshow %}
          {%endblock slideshow%}

           </p>
         </div>
         {% include "articles/messages.html"%}
        </div>
      </div>
    </header>
    <footer class="footer text-muted">
      <div class="container text-center">
        <p class="float-right">
          <a href="#"><input type="button" value="Back To Top"/></a>
        </p>
        <p>CNWW &copy; Cryptonews Worlwide {%now 'Y'%}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <script src="{%static 'js/popper.min.js'%}"></script>
    <script src="{%static 'js/bootstrap.min.js'%}"></script>
  </body>
</html>

articles/templates/articles/create_article.html
{%extends 'articles/base.html'%}
{% load bootstrap4 %}
{% load crispy_forms_tags %}
{%load staticfiles%}
{%block article_form %}
<script type="text/javascript" src="/static/js/jquery.js"></script>
<script type="text/javascript" src="/static/js/jquery.jqtransform.js"></script>

<form class="jqtransform" method="post" action="{% url 'articles:create_article'%}" enctype="multipart/form-data">
    <div class="rowElem">
        {%csrf_token%}
        {{form|crispy}}
    </div>
    <input class="btn btn-success" type="submit" value="Create Article" />
</form>
<script src="/static/js/slugify.js"></script>
{% endblock %}

articles/templates/articles/messages.html
   {% if messages %}
        <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{message.tags}}"{% endif %}>{% if "html_safe" in message.tags%}{{message|safe}}{% else%}{{message}}{% endif%}</li>
        {% endfor %}
        </ul>
    {% endif %}

cnewsww/templates/cnewsww/datas.html
{%block search%}
{{quote}}
{%endblock%}

cnewsww/templates/cnewsww/home.html
{% load bootstrap4 %}
{% load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{url 'static/media/coin.png'}">

    <title>CNWW website</title>

    <!-- Bootstrap core CSS -->
    <link href="{%static 'css/bootstrap.min.css'%}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/styler.css' %}">
  </head>

  <body>

    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="{url 'cryptos:home'}">CNWW Latest News</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav ml-auto">
            <a class="nav-item nav-link active" href="{url 'cryptos:home'}">Home <span class="sr-only">(current)</span></a>
            <a class="nav-item nav-link" href="/articles">Blog</a>
          </div>
        </div>
      </nav>
      <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
          <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
              <h4 class="text-white">About</h4>
              <p class="text-muted">I am a software enthusiast with persionate interest in how Cryptocurrencies can help improve daily living.</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
              <h4 class="text-white">Contact</h4>
              <ul class="list-unstyled">
                <li><a href="mailto: olofintuyiadeolu@outlook.co.uk" class="text-white"><input type="button" value="Email Me"/></a></li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      <nav class="navbar navbar-dark bg-dark">
        <form method="GET" class="form-inline">
          {%csrf_token%}
          <input class="form-control mr-sm-2" name="q" type="search" placeholder="Cryptocurrency" action="{url 'cryptos:single'}" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search Cryptocurrency</button>
        </form>
      </nav>
      <div class="navbar navbar-dark bg-dark shadow-sm">
        <div class="container d-flex justify-content-between">
          <a href="#" class="navbar-brand d-flex align-items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="mr-2"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"></path><circle cx="12" cy="13" r="4"></circle></svg>
            <strong>Album</strong>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
        </div>
      </div>
    </header>

    <main role="main">

      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Crypto News Worldwide</h1>
          <p class="lead text-muted">Get updated crypto currency happenings all over the world and get updated price of the top 10 coins</p>
          <p>
              <a href="#" class="btn-group btn btn-primary my-2" target="">Twitter</a>
              <a class="btn-group btn btn-primary my-2" target="_blank" href="#">E-Mail</a>
              <a href="#" class="btn btn-secondary my-2" target="_blank">Facebook</a>
          </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
          <div class="container">

              <table class="table table-striped table-dark table-hover table-bordered ml-auto">
                  <thead>
                      <tr>
                          <th scope="col">NAME</th>
                          <th scope="col">CURRENT PRICE</th>
                          <th scope="col">LAST UPDATED</th>
                          <th scope="col">MARKET CAP</th>
                      </tr>
                  </thead>

                  {% for key,value in data.DISPLAY.items %}
                  <tbody>
                      <tr>
                          <td>{{key}}</td>
                          <td>{{value.USD.PRICE}}</td>
                          <td>{{value.USD.LASTUPDATE}}</td>
                          <td>{{value.USD.MKTCAP}}</td>
                      </tr>
                      {% endfor %}
                  </tbody>
              </table>

              <div class="album py-5 bg-dark">
                  <div class="container">
                      <div class="row ml-auto">
                          {% for x in api.Data %}
                          <div class="col-sm">
                              <div class="card" style="width: 18rem;">
                                  <img class="card-img-top" src="{{x.imageurl}}" alt="{{x.source}}">
                                  <div class="card-body">
                                      <h5 class="card-title">{{x.title}}</h5>
                                      <h4><p class="card-text">{{x.body}}</p></h4>
                                      <a href="{{x.url}}" class="btn btn-secondary">Read More</a>
                                  </div>
                              </div>
                              </br>
                          </div>
                          {% endfor %}
                      </div>
                  </div>
              </div>
              <div class="pagination">
                  <span class="step-links">
                      {% if qset.has_previous %}
                      <a href="?page=1">&laquo; first</a>
                      <a href="?page={{ qset.previous_page_number }}">previous</a>
                      {% endif %}

                      <span class="current">
                          Page {{ qset.number }} of {{qset.paginator.num_pages }}.
                      </span>

                      {% if contacts.has_next %}
                      <a href="?page={{ qset.next_page_number }}">next</a>
                      <a href="?page={{ qset.paginator.num_pages }}">last &raquo;</a>
                      {% endif %}
                  </span>
              </div>
          </div>
      </div>

    </main>

    <footer class="text-muted">
      <div class="container text-center">
        <p class="float-right">
          <a href="#"><input type="button" value="Back To Top"/></a>
        </p>
        <p>CNWW &copy; Cryptonews Worlwide {%now 'Y'%}</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>